package com;
// Generated Jul 11, 2016 10:54:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Attenders generated by hbm2java
 */
public class Attenders implements java.io.Serializable {

	private int aid;
	private String aname;
	private Set eventAttenderses = new HashSet(0);

	public Attenders() {
	}

	public Attenders(int aid) {
		this.aid = aid;
	}

	public Attenders(int aid, String aname, Set eventAttenderses) {
		this.aid = aid;
		this.aname = aname;
		this.eventAttenderses = eventAttenderses;
	}

	public int getAid() {
		return this.aid;
	}

	public void setAid(int aid) {
		this.aid = aid;
	}

	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	public Set getEventAttenderses() {
		return this.eventAttenderses;
	}

	public void setEventAttenderses(Set eventAttenderses) {
		this.eventAttenderses = eventAttenderses;
	}

}
