package com;
// Generated Jul 11, 2016 10:54:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private int compId;
	private String compName;
	private Set events = new HashSet(0);

	public Company() {
	}

	public Company(int compId) {
		this.compId = compId;
	}

	public Company(int compId, String compName, Set events) {
		this.compId = compId;
		this.compName = compName;
		this.events = events;
	}

	public int getCompId() {
		return this.compId;
	}

	public void setCompId(int compId) {
		this.compId = compId;
	}

	public String getCompName() {
		return this.compName;
	}

	public void setCompName(String compName) {
		this.compName = compName;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
