package com;
// Generated Jul 11, 2016 10:54:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private int eid;
	private Company company;
	private Location location;
	private String ename;
	private Set speakers = new HashSet(0);
	private Set managers = new HashSet(0);
	private Set eventAttenderses = new HashSet(0);

	public Event() {
	}

	public Event(int eid) {
		this.eid = eid;
	}

	public Event(int eid, Company company, Location location, String ename, Set speakers, Set managers,
			Set eventAttenderses) {
		this.eid = eid;
		this.company = company;
		this.location = location;
		this.ename = ename;
		this.speakers = speakers;
		this.managers = managers;
		this.eventAttenderses = eventAttenderses;
	}

	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Set getSpeakers() {
		return this.speakers;
	}

	public void setSpeakers(Set speakers) {
		this.speakers = speakers;
	}

	public Set getManagers() {
		return this.managers;
	}

	public void setManagers(Set managers) {
		this.managers = managers;
	}

	public Set getEventAttenderses() {
		return this.eventAttenderses;
	}

	public void setEventAttenderses(Set eventAttenderses) {
		this.eventAttenderses = eventAttenderses;
	}

}
