package com;
// Generated Jul 11, 2016 10:54:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * EventAttenders generated by hbm2java
 */
public class EventAttenders implements java.io.Serializable {

	private EventAttendersId id;
	private Attenders attenders;
	private Event event;

	public EventAttenders() {
	}

	public EventAttenders(EventAttendersId id, Attenders attenders, Event event) {
		this.id = id;
		this.attenders = attenders;
		this.event = event;
	}

	public EventAttendersId getId() {
		return this.id;
	}

	public void setId(EventAttendersId id) {
		this.id = id;
	}

	public Attenders getAttenders() {
		return this.attenders;
	}

	public void setAttenders(Attenders attenders) {
		this.attenders = attenders;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

}
