package com;
// Generated Jul 11, 2016 10:54:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	private int locId;
	private String locName;
	private Set events = new HashSet(0);

	public Location() {
	}

	public Location(int locId) {
		this.locId = locId;
	}

	public Location(int locId, String locName, Set events) {
		this.locId = locId;
		this.locName = locName;
		this.events = events;
	}

	public int getLocId() {
		return this.locId;
	}

	public void setLocId(int locId) {
		this.locId = locId;
	}

	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
