package com;
// Generated Jul 11, 2016 10:54:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private int mid;
	private Event event;
	private String mname;

	public Manager() {
	}

	public Manager(int mid) {
		this.mid = mid;
	}

	public Manager(int mid, Event event, String mname) {
		this.mid = mid;
		this.event = event;
		this.mname = mname;
	}

	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

}
