package com;
// Generated Jul 11, 2016 10:54:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Speaker generated by hbm2java
 */
public class Speaker implements java.io.Serializable {

	private int speakid;
	private String SName;
	private Set events = new HashSet(0);

	public Speaker() {
	}

	public Speaker(int speakid) {
		this.speakid = speakid;
	}

	public Speaker(int speakid, String SName, Set events) {
		this.speakid = speakid;
		this.SName = SName;
		this.events = events;
	}

	public int getSpeakid() {
		return this.speakid;
	}

	public void setSpeakid(int speakid) {
		this.speakid = speakid;
	}

	public String getSName() {
		return this.SName;
	}

	public void setSName(String SName) {
		this.SName = SName;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

}
